/**
 * Where a customer can send a transfer: the banks operating in Ethiopia, then
 * the mobile wallets. Stored on the sale by name.
 */
export const BANKS = [
  'Commercial Bank of Ethiopia (CBE)',
  'Awash Bank',
  'Dashen Bank',
  'Bank of Abyssinia',
  'Cooperative Bank of Oromia (Coopbank)',
  'Hibret Bank',
  'Wegagen Bank',
  'Nib International Bank',
  'Oromia Bank',
  'Zemen Bank',
  'Bunna Bank',
  'Berhan Bank',
  'Abay Bank',
  'Lion International Bank',
  'Enat Bank',
  'Addis International Bank',
  'Global Bank Ethiopia',
  'Debub Global Bank',
  'Amhara Bank',
  'Siinqee Bank',
  'Sidama Bank',
  'Ahadu Bank',
  'Tsehay Bank',
  'Gadaa Bank',
  'Hijra Bank',
  'ZamZam Bank',
  'Tsedey Bank',
  'Shabelle Bank',
  'Rammis Bank',
  'Goh Betoch Bank',
  'Development Bank of Ethiopia',
  'Telebirr',
  'M-Pesa',
] as const
